### ISSUE TITLE
please help with the update of-capes  to version 1.21

### ISSUE THREAD

**Issue by forditt** [SuchBlue/such.blue#4]
I couldn't find your contacts so I leave my request here if you have free time could you please update the mod to version 1.21?

https://github.com/SuchBlue/of-capes

**Comment by SuchBlue** [comment]
Hi,
I can.. but honestly the mod is made useless by the [Capes](https://modrinth.com/mod/capes) mod, which has more functionality and also supports OptiFine capes.

If there's any reason as to why this mod should continue existing, feel free to ask but I think the Capes mod is a better alternative.

**Comment by forditt** [comment]
I agree that the capes mod has more functionality, but that's what doesn't suit me, I like the minimalism of the mod you updated, since I only use the optifine cloak, and as far as I've noticed, the of-capes mod is more stable compared to capes. Thank you for your understanding, and I still hope you will think about it 

![image](https://github.com/SuchBlue/such.blue/assets/105544922/b39e204f-ee1f-4134-8921-5d474d1b291c)

**Comment by SuchBlue** [comment]
[Done](https://github.com/SuchBlue/of-capes/releases/tag/2.0.2)! 😀 @forditt

**Comment by forditt** [comment]
> [Done](https://github.com/SuchBlue/of-capes/releases/tag/2.0.2)! 😀 @forditt

thank you very much!!!!!!! 😲

**Comment by forditt** [comment]
I am very satisfied, thank you for your work

**Comment by forditt** [comment]
![image](https://github.com/SuchBlue/such.blue/assets/105544922/5107b223-a12e-4389-9b16-f413c708f2eb)
unfortunately the cloak editor button does not work

**Comment by forditt** [comment]
I am also from Ukraine, so I play in Ukrainian, you can also add a Ukrainian translation.
[uk_ua.json](https://github.com/user-attachments/files/16113553/uk_ua.json)

I'm sorry that I give so many tasks, everything is only according to your wish
